/**
 * System domain types — windows, dialogs, password storage, system ops,
 * auto-update, menu, keyboard shortcuts, and project URLs.
 */

export type {
  CloseWindowRequest,
  CloseWindowResponse,
  CreateWindowResponse,
  FocusWindowRequest,
  FocusWindowResponse,
  GetAllWindowsResponse,
  GetCurrentWindowResponse,
  GetPasswordRequest,
  GetPasswordResponse,
  HasPasswordRequest,
  HasPasswordResponse,
  IsPasswordStorageAvailableResponse,
  MenuAction,
  OpenExternalRequest,
  OpenExternalResponse,
  OpenFileDialogRequest,
  OpenFileDialogResponse,
  PresetName,
  RemovePasswordRequest,
  RemovePasswordResponse,
  SaveFileDialogRequest,
  SaveFileDialogResponse,
  SavePasswordRequest,
  SavePasswordResponse,
  ShortcutAction,
  ShortcutBinding,
  ShortcutModifiers,
  ShortcutPreset,
  ShortcutsUpdatePayload,
  ShowItemInFolderRequest,
  ShowItemInFolderResponse,
  UpdateProgress,
  UpdateStatus,
  WriteFileRequest,
  WriteFileResponse,
} from '../../types';
