import type { WriteFileRequest } from '@shared/types';
import { Buffer } from 'node:buffer';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * File Write API Tests
 *
 * Tests for the file write IPC handler in dialog.ts.
 * Verifies text file writing, atomic write pattern, and error handling.
 */

// ============ Mock electron modules ============

const { mockHandlers } = vi.hoisted(() => {
  const mockHandlers = new Map<string, (...args: unknown[]) => unknown>();
  return { mockHandlers };
});

vi.mock('electron', () => {
  return {
    app: {
      isPackaged: false,
      getPath: () => '/tmp',
      getVersion: () => '1.0.0',
      getName: () => 'test-app',
    },
    ipcMain: {
      handle: (channel: string, handler: (...args: unknown[]) => unknown) => {
        mockHandlers.set(channel, handler);
      },
      removeHandler: (channel: string) => {
        mockHandlers.delete(channel);
      },
    },
    dialog: {
      showOpenDialog: vi.fn(),
      showSaveDialog: vi.fn(),
    },
  };
});

// Import after mocking
const { setupDialogHandlers } = await import('./dialog');
setupDialogHandlers();

// Helper to invoke IPC handlers
interface IpcMainInvokeEvent {
  sender: unknown;
}

async function invokeHandler<T>(
  channel: string,
  ...args: unknown[]
): Promise<T> {
  const handler = mockHandlers.get(channel);
  if (!handler) {
    throw new Error(`No handler registered for channel: ${channel}`);
  }

  const mockEvent = {} as IpcMainInvokeEvent;
  return handler(mockEvent, ...args) as Promise<T>;
}

// ============ Tests ============

describe('file Write IPC Handler', () => {
  let tempDir: string;

  beforeEach(() => {
    // Create temp directory for tests
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'file-write-test-'));
  });

  afterEach(() => {
    // Clean up temp directory
    if (tempDir && fs.existsSync(tempDir)) {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  describe('basic File Writing', () => {
    it('should write text content to a file', async () => {
      const testFilePath = path.join(tempDir, 'test.sql');
      const testContent = 'SELECT * FROM users;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBe(Buffer.from(testContent, 'utf8').length);

      // Verify file was created with correct content
      expect(fs.existsSync(testFilePath)).toBe(true);
      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(testContent);
    });

    it('should write multi-line SQL content', async () => {
      const testFilePath = path.join(tempDir, 'migration.sql');
      const testContent = `-- Migration SQL
-- Generated by SQL Pro

INSERT INTO users (name, email) VALUES ('John', 'john@example.com');
UPDATE products SET price = 9.99 WHERE id = 1;
DELETE FROM temp_data WHERE created_at < '2024-01-01';`;

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      expect(result.success).toBe(true);

      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(testContent);
    });

    it('should write to nested directories if they exist', async () => {
      const nestedDir = path.join(tempDir, 'nested', 'folder');
      fs.mkdirSync(nestedDir, { recursive: true });

      const testFilePath = path.join(nestedDir, 'test.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(fs.existsSync(testFilePath)).toBe(true);
    });
  });

  describe('atomic Write Pattern', () => {
    it('should use atomic write by default', async () => {
      const testFilePath = path.join(tempDir, 'atomic-test.sql');
      const testContent = 'SELECT * FROM atomic_test;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
        // atomic defaults to true
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(fs.existsSync(testFilePath)).toBe(true);

      // Verify no temp files left behind
      const files = fs.readdirSync(tempDir);
      expect(files.filter((f) => f.startsWith('.tmp_'))).toHaveLength(0);
    });

    it('should support non-atomic write', async () => {
      const testFilePath = path.join(tempDir, 'non-atomic.sql');
      const testContent = 'SELECT * FROM non_atomic;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
        atomic: false,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(fs.existsSync(testFilePath)).toBe(true);
    });

    it('should clean up temp file on atomic write failure', async () => {
      // Create a read-only directory to cause failure
      const readOnlyDir = path.join(tempDir, 'readonly');
      fs.mkdirSync(readOnlyDir);

      // Create a file with the target name to simulate rename failure
      const existingFile = path.join(readOnlyDir, 'existing.sql');
      fs.writeFileSync(existingFile, 'existing');
      fs.chmodSync(existingFile, 0o444); // read-only

      const testFilePath = path.join(readOnlyDir, 'new-file.sql');
      const testContent = 'SELECT 1;';

      // This should succeed since the target doesn't exist yet
      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      // Should succeed since target path is writeable
      expect(result.success).toBe(true);

      // Cleanup
      fs.chmodSync(existingFile, 0o644);
    });

    it('should preserve original file content when atomic write fails', async () => {
      // Create an existing file with original content
      const testFilePath = path.join(tempDir, 'original.sql');
      const originalContent = 'SELECT * FROM original;';
      fs.writeFileSync(testFilePath, originalContent);

      // Make the directory read-only to cause rename failure
      // First write to temp will succeed, but rename will fail

      // Create a subdirectory for this test
      const testDir = path.join(tempDir, 'preserve-test');
      fs.mkdirSync(testDir);
      const targetFile = path.join(testDir, 'target.sql');
      const originalTargetContent = 'ORIGINAL CONTENT';
      fs.writeFileSync(targetFile, originalTargetContent);

      // Make the target file read-only
      fs.chmodSync(targetFile, 0o444);

      const request: WriteFileRequest = {
        filePath: targetFile,
        content: 'NEW CONTENT THAT SHOULD NOT APPEAR',
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      // If write failed, original content should be preserved
      if (!result.success) {
        const currentContent = fs.readFileSync(targetFile, 'utf8');
        expect(currentContent).toBe(originalTargetContent);
      }

      // Cleanup
      fs.chmodSync(targetFile, 0o644);

      // Verify no temp files left behind in any case
      const files = fs.readdirSync(testDir);
      expect(files.filter((f) => f.startsWith('.tmp_'))).toHaveLength(0);
    });

    it('should not create partial file at target path on temp file write failure', async () => {
      // Create a test directory where temp file creation will fail
      const failDir = path.join(tempDir, 'fail-dir');
      fs.mkdirSync(failDir);

      const targetFile = path.join(failDir, 'target.sql');

      // Verify target file doesn't exist
      expect(fs.existsSync(targetFile)).toBe(false);

      // Make directory read-only so temp file creation fails
      fs.chmodSync(failDir, 0o444);

      const request: WriteFileRequest = {
        filePath: targetFile,
        content: 'This content should not appear anywhere',
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);

      // Restore permissions for verification
      fs.chmodSync(failDir, 0o755);

      // Target file should NOT exist - no partial write
      expect(fs.existsSync(targetFile)).toBe(false);

      // No temp files should be left behind
      const files = fs.readdirSync(failDir);
      expect(files.filter((f) => f.startsWith('.tmp_'))).toHaveLength(0);
    });

    it('should clean up temp files when rename fails', async () => {
      const testDir = path.join(tempDir, 'rename-fail-test');
      fs.mkdirSync(testDir);

      const targetFile = path.join(testDir, 'locked.sql');

      // Create target file and make it read-only
      fs.writeFileSync(targetFile, 'locked content');
      fs.chmodSync(targetFile, 0o444);

      const request: WriteFileRequest = {
        filePath: targetFile,
        content: 'new content',
        atomic: true,
      };

      // Invoke the handler - success depends on OS behavior with atomic rename
      await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      // Whether it succeeded or failed, there should be no temp files left behind
      const files = fs.readdirSync(testDir);
      const tempFiles = files.filter((f) => f.startsWith('.tmp_'));
      expect(tempFiles).toHaveLength(0);

      // Cleanup
      fs.chmodSync(targetFile, 0o644);
    });

    it('should verify temp file is in same directory as target for atomic rename', async () => {
      // This test verifies the atomic rename works across the same filesystem
      const testFilePath = path.join(tempDir, 'same-dir-test.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
        atomic: true,
      };

      // During the write, we expect temp file to be in tempDir
      // We can't easily observe this during execution, but we can verify
      // the final result has no temp files and the target file exists
      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(fs.existsSync(testFilePath)).toBe(true);

      // Verify no temp files remain
      const files = fs.readdirSync(tempDir);
      expect(files.filter((f) => f.startsWith('.tmp_'))).toHaveLength(0);

      // Content should be exactly as written (no partial data)
      const content = fs.readFileSync(testFilePath, 'utf8');
      expect(content).toBe(testContent);
    });

    it('should handle overwriting existing file atomically', async () => {
      const testFilePath = path.join(tempDir, 'overwrite-test.sql');
      const originalContent = 'ORIGINAL SQL CONTENT';
      const newContent = 'NEW SQL CONTENT THAT REPLACES ORIGINAL';

      // Create original file
      fs.writeFileSync(testFilePath, originalContent);
      expect(fs.readFileSync(testFilePath, 'utf8')).toBe(originalContent);

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: newContent,
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);

      // File should have new content
      const finalContent = fs.readFileSync(testFilePath, 'utf8');
      expect(finalContent).toBe(newContent);

      // No temp files left
      const files = fs.readdirSync(tempDir);
      expect(files.filter((f) => f.startsWith('.tmp_'))).toHaveLength(0);
    });

    it('should write complete content in atomic mode (no partial writes)', async () => {
      const testFilePath = path.join(tempDir, 'complete-write-test.sql');

      // Generate content with known checksum characteristics
      const lines: string[] = [];
      for (let i = 0; i < 100; i++) {
        lines.push(
          `-- Line ${i}: INSERT INTO test VALUES (${i}, 'data_${i}');`
        );
      }
      const testContent = lines.join('\n');
      const expectedLength = Buffer.from(testContent, 'utf8').length;

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBe(expectedLength);

      // Read back and verify complete content
      const writtenContent = fs.readFileSync(testFilePath, 'utf8');
      expect(writtenContent).toBe(testContent);
      expect(writtenContent.split('\n').length).toBe(100);

      // Verify first and last lines to confirm no truncation
      expect(writtenContent.startsWith('-- Line 0:')).toBe(true);
      expect(writtenContent.endsWith("'data_99');")).toBe(true);
    });
  });

  describe('encoding Support', () => {
    it('should use utf8 encoding by default', async () => {
      const testFilePath = path.join(tempDir, 'utf8.sql');
      const testContent = '-- Unicode: 日本語 テスト\nSELECT * FROM users;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);

      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(testContent);
    });

    it('should support custom encoding', async () => {
      const testFilePath = path.join(tempDir, 'utf16.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
        encoding: 'utf16le',
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      expect(result.success).toBe(true);
      // UTF-16LE uses 2 bytes per character
      expect(result.bytesWritten).toBe(testContent.length * 2);
    });
  });

  describe('error Handling', () => {
    it('should handle non-existent directory', async () => {
      const testFilePath = path.join(tempDir, 'non-existent-dir', 'test.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);
      expect(result.error).toContain('directory does not exist');
    });

    it('should handle permission denied error', async () => {
      // Create a read-only directory
      const readOnlyDir = path.join(tempDir, 'readonly-dir');
      fs.mkdirSync(readOnlyDir);
      fs.chmodSync(readOnlyDir, 0o444);

      const testFilePath = path.join(readOnlyDir, 'test.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);
      expect(result.error).toContain('Permission denied');

      // Cleanup
      fs.chmodSync(readOnlyDir, 0o755);
    });

    it('should return user-friendly error messages', async () => {
      const testFilePath = path.join(tempDir, 'not-exist', 'test.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);
      expect(result.error).toBeDefined();
      // Error message should be user-friendly
      expect(result.error).not.toContain('ENOENT');
    });

    it('should handle writing to a directory path (EISDIR)', async () => {
      // Use the temp directory itself as the file path
      const request: WriteFileRequest = {
        filePath: tempDir,
        content: 'SELECT 1;',
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);
      expect(result.error).toContain('directory');
    });

    it('should handle read-only file overwrite', async () => {
      // Create a read-only file
      const readOnlyFile = path.join(tempDir, 'readonly-file.sql');
      fs.writeFileSync(readOnlyFile, 'original content');
      fs.chmodSync(readOnlyFile, 0o444);

      const request: WriteFileRequest = {
        filePath: readOnlyFile,
        content: 'new content',
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      // Atomic write creates temp file then renames, so this should fail on rename
      // if the target is read-only (depends on OS behavior)
      // The test verifies that an error is returned, not a crash
      if (!result.success) {
        expect(result.error).toBeDefined();
        // Error should be user-friendly (not raw error code)
        expect(result.error).not.toMatch(/^E[A-Z]+$/);
      }

      // Cleanup
      fs.chmodSync(readOnlyFile, 0o644);
    });

    it('should handle empty file path gracefully', async () => {
      const request: WriteFileRequest = {
        filePath: '',
        content: 'SELECT 1;',
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);
      expect(result.error).toBeDefined();
    });

    it('should handle deeply nested non-existent path', async () => {
      const deepPath = path.join(
        tempDir,
        'level1',
        'level2',
        'level3',
        'level4',
        'test.sql'
      );

      const request: WriteFileRequest = {
        filePath: deepPath,
        content: 'SELECT 1;',
      };

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      expect(result.success).toBe(false);
      expect(result.error).toContain('directory does not exist');
    });

    it('should handle special characters in file path', async () => {
      // Test with spaces and valid special chars in path
      const specialDir = path.join(tempDir, 'folder with spaces');
      fs.mkdirSync(specialDir);

      const testFilePath = path.join(specialDir, 'file-name_v2.0.sql');
      const testContent = 'SELECT 1;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(fs.existsSync(testFilePath)).toBe(true);
    });

    it('should handle file path with unicode characters', async () => {
      // Test with unicode characters in path
      const unicodeDir = path.join(tempDir, '文件夹');
      fs.mkdirSync(unicodeDir);

      const testFilePath = path.join(unicodeDir, 'テスト.sql');
      const testContent = 'SELECT * FROM 测试表;';

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(fs.existsSync(testFilePath)).toBe(true);

      const content = fs.readFileSync(testFilePath, 'utf8');
      expect(content).toBe(testContent);
    });

    it('should return error for null content', async () => {
      const testFilePath = path.join(tempDir, 'null-content.sql');

      const request = {
        filePath: testFilePath,
        content: null,
      } as unknown as WriteFileRequest;

      const result = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', request);

      // Should either fail or handle null gracefully
      if (!result.success) {
        expect(result.error).toBeDefined();
      }
    });

    it('should handle empty content string', async () => {
      const testFilePath = path.join(tempDir, 'empty-content.sql');

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: '',
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      // Empty content should be valid
      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBe(0);
      expect(fs.existsSync(testFilePath)).toBe(true);
      expect(fs.readFileSync(testFilePath, 'utf8')).toBe('');
    });

    it('should verify all error messages are actionable', async () => {
      // Test various error scenarios and verify messages provide guidance

      // Test 1: Non-existent directory - should suggest valid location
      const result1 = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', {
        filePath: path.join(tempDir, 'not-exist', 'test.sql'),
        content: 'test',
      });
      expect(result1.error).toContain('choose');

      // Test 2: Permission denied - should suggest checking access
      const readOnlyDir = path.join(tempDir, 'perm-test');
      fs.mkdirSync(readOnlyDir);
      fs.chmodSync(readOnlyDir, 0o444);

      const result2 = await invokeHandler<{
        success: boolean;
        error?: string;
      }>('file:write', {
        filePath: path.join(readOnlyDir, 'test.sql'),
        content: 'test',
      });
      expect(result2.error).toContain('access');

      // Cleanup
      fs.chmodSync(readOnlyDir, 0o755);
    });
  });

  describe('sQL File Save Scenarios', () => {
    it('should save DataDiffSQLGenerator sync SQL', async () => {
      const testFilePath = path.join(
        tempDir,
        `data_sync_${new Date().toISOString().split('T')[0]}.sql`
      );
      const syncSQL = `-- Data Sync SQL
-- Generated from data comparison

BEGIN TRANSACTION;

INSERT INTO target_table (id, name, value)
VALUES (1, 'New Row', 100);

UPDATE target_table
SET value = 200
WHERE id = 2;

DELETE FROM target_table
WHERE id = 3;

COMMIT;`;

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: syncSQL,
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBeGreaterThan(0);

      // Verify content
      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(syncSQL);
      expect(fileContent).toContain('INSERT INTO');
      expect(fileContent).toContain('UPDATE');
      expect(fileContent).toContain('DELETE FROM');
    });

    it('should save MigrationPreview migration SQL', async () => {
      const testFilePath = path.join(
        tempDir,
        `migration_${new Date().toISOString().split('T')[0]}.sql`
      );
      const migrationSQL = `-- Migration SQL
-- Source: dev_database
-- Target: prod_database
-- Generated at: ${new Date().toISOString()}

-- Create new tables
CREATE TABLE IF NOT EXISTS new_feature (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Add new columns
ALTER TABLE users ADD COLUMN last_login TEXT;

-- Create new indexes
CREATE INDEX IF NOT EXISTS idx_users_last_login ON users(last_login);`;

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: migrationSQL,
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBeGreaterThan(0);

      // Verify content
      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(migrationSQL);
      expect(fileContent).toContain('CREATE TABLE');
      expect(fileContent).toContain('ALTER TABLE');
      expect(fileContent).toContain('CREATE INDEX');
    });

    it('should handle large SQL files', async () => {
      const testFilePath = path.join(tempDir, 'large.sql');

      // Generate a large SQL file (simulate many rows)
      let largeSQL = '-- Large SQL file test\n\n';
      for (let i = 0; i < 1000; i++) {
        largeSQL += `INSERT INTO users (id, name, email) VALUES (${i}, 'User ${i}', 'user${i}@example.com');\n`;
      }

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: largeSQL,
        atomic: true,
      };

      const result = await invokeHandler<{
        success: boolean;
        bytesWritten?: number;
      }>('file:write', request);

      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBeGreaterThan(50000); // Should be quite large

      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(largeSQL);
    });
  });

  describe('dialog Cancellation Handling', () => {
    it('should verify save dialog cancellation returns proper response format', async () => {
      // Import the dialog mock to control its behavior
      const { dialog } = await import('electron');

      // Mock the save dialog to simulate user cancellation
      // Cast to any to handle the case where filePath is undefined on cancellation
      vi.mocked(dialog.showSaveDialog).mockResolvedValueOnce({
        canceled: true,
        filePath: undefined as unknown as string,
      });

      const result = await invokeHandler<{
        success: boolean;
        canceled?: boolean;
        filePath?: string;
      }>('dialog:save-file', {
        title: 'Save Test',
        filters: [{ name: 'SQL Files', extensions: ['sql'] }],
      });

      // Dialog cancellation should return success=true with canceled=true
      // This allows the renderer to distinguish between errors and user cancellation
      expect(result.success).toBe(true);
      expect(result.canceled).toBe(true);
      expect(result.filePath).toBeUndefined();
    });

    it('should verify save dialog success returns file path', async () => {
      const { dialog } = await import('electron');
      const expectedPath = '/tmp/test-save.sql';

      // Mock successful save dialog
      vi.mocked(dialog.showSaveDialog).mockResolvedValueOnce({
        canceled: false,
        filePath: expectedPath,
      });

      const result = await invokeHandler<{
        success: boolean;
        canceled?: boolean;
        filePath?: string;
      }>('dialog:save-file', {
        title: 'Save Test',
        filters: [{ name: 'SQL Files', extensions: ['sql'] }],
      });

      expect(result.success).toBe(true);
      expect(result.canceled).toBeFalsy();
      expect(result.filePath).toBe(expectedPath);
    });
  });

  describe('special Characters', () => {
    it('should handle SQL with special characters', async () => {
      const testFilePath = path.join(tempDir, 'special.sql');
      const testContent = `-- Special characters test
INSERT INTO messages (content) VALUES ('Hello "World"');
INSERT INTO messages (content) VALUES ('It''s a test');
INSERT INTO messages (content) VALUES ('Line 1\\nLine 2');
INSERT INTO messages (content) VALUES ('Tab\\there');`;

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);

      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(testContent);
    });

    it('should handle SQL with emoji', async () => {
      const testFilePath = path.join(tempDir, 'emoji.sql');
      const testContent = `-- Emoji test 🎉
INSERT INTO posts (content) VALUES ('Hello World! 👋');`;

      const request: WriteFileRequest = {
        filePath: testFilePath,
        content: testContent,
      };

      const result = await invokeHandler<{
        success: boolean;
      }>('file:write', request);

      expect(result.success).toBe(true);

      const fileContent = fs.readFileSync(testFilePath, 'utf8');
      expect(fileContent).toBe(testContent);
    });
  });
});
